name: "Patterson"
picture: "assets/img/picture.jpg"
bio: "Programmer python"
meta:
  lang: "pt_br"
  description: "Programmer python"
  title: "Patterson"
  author: "Patterson"
  siteUrl: "https://pattersonrptr.github.io/python-link-tree/"
links:
  - name: "Github"
    url: "https://github.com/pattersonrptr"
  # - name: "Dev.to"
  #   url: "https://dev.to/king_triton"
  # - name: "Patreon"
  #   url: "https://www.patreon.com/king_triton"
  # - name: "Telegram"
  #   url: "https://t.me/king_triton"
  - name: "Instagram"
    url: "https://www.instagram.com/patterson_00110111/"
  - name: "Medium"
    url: "https://medium.com/@pattersonjunior"
  # - name: ""
  #   url: ""
theme: "custom"
